### PR TITLE
update to webpack 4, update dependencies, update node, fix some eslint warnings

### PR DESCRIPTION
**Pull request by glebtv**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/sass-resources-loader/95)

### CODE REVIEW

**Comment by glebtv** [comment]
1) I updated all of the dependencies. ```yarn outdated``` is empty both in package and in example.
2) Only tested on webpack 4 and node 12, tested on example from this repo and one medium-sized app.
3) Updated eslint configs, all of the code style changes are from updated eslint configs
4) Added a css-format test file, because in a real app I had a problem with CSS files (adding import directives to CSS file causes SASS to break for me with strange errors) - but was unable to reproduce in an example, solved for me by excluding *.css from this loader in my app.
5) CI fail is due to eslint errors on current code and new versions of eslint configs, I am not really sure how to fix them (if you want, I can add eslint-ignore on them)

**Comment by justin808** [comment]
Sounds good on the above! @glebtv 

For the consistent-return, I think it's best to fix the code so it passes this. That means adding a few `return undefined;` 
```
/home/travis/build/shakacode/sass-resources-loader/src/loader.js
  13:16  error  Expected to return a value at the end of function  consistent-return
  20:3   error  Unexpected dangling '_' in '__DEBUG__'             no-underscore-dangle
  75:2   error  Unnecessary semicolon                              no-extra-semi
```
Last one is easy. 
2nd one maybe can be ignored.

```
/home/travis/build/shakacode/sass-resources-loader/src/utils/flattenArray.js
  1:36  error  Use the spread operator instead of '.apply()'  prefer-spread
```

https://eslint.org/docs/rules/prefer-spread

```
export default multidimensional => [].concat(...multidimensional);
```


/home/travis/build/shakacode/sass-resources-loader/src/utils/rewriteImports.js
  15:16  error  Expected to return a value at the end of function  consistent-return
/home/travis/build/shakacode/sass-resources-loader/test/index.test.js
   60:22  error  Unexpected require()  global-require
   69:22  error  Unexpected require()  global-require
   78:22  error  Unexpected require()  global-require
  128:32  error  Unexpected require()  global-require
```

I think these should be ignored in the file.

**Comment by Judahmeek** [comment]
@justin808 do you want me to complete this PR?

**Comment by glebtv** [comment]
@justin808 Thank you for the feedback, I have fixed all the remaining ESLint problems.

**Comment by justin808** [comment]
@glebtv @Judahmeek Can the rest of these be closed: https://github.com/shakacode/sass-resources-loader/pulls ?

**Pull request merged**
