### PR TITLE
Setup Glob files matching

### PR DESCRIPTION
**Pull request by rtivital**
Issue https://github.com/shakacode/sass-resources-loader/issues/10

Enabled glob features. Now all patterns like `./src/resources/*.scss` or `./src/resources/*/**.scss` will be matched. Single files like `./src/resources/variables.scss` will be processed as well.

---
This change is [Reviewable](https://reviewable.io/reviews/shakacode/sass-resources-loader/11)

### CODE REVIEW

**Comment by justin808** [comment]
@rtivital Big thanks! 

@alexfedoseev This looks good. I'll let you mark the files as reviewed.

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/sass-resources-loader/11#-:-KNOi6m9Ajekg0L72u_1:303228972)*

**Comment by justin808** [comment]
@alexfedoseev Let's merge and release if you like this one.

**Comment by alexfedoseev** [comment]
@rtivital Thanks for PR! :lgtm: Also we should add note about this part to README w/ warning that the order of globed assets is not guarantied. Will merge and release this after README update, thanks! :+1: 

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/shakacode/sass-resources-loader/11#-:-KN_Jo0RvUamYbVmVUB0:628417006)*

**Comment by justin808** [comment]
@alexfedoseev we should merge and release this once CHANGELOG.MD and README.md are updated by @rtivital!

**Comment by justin808** [comment]
@rtivital Can you please do the entry for the CHANGELOG.md and README.md? We'd like to get this merged.

**Comment by rtivital** [comment]
@justin808 updated the README file, not sure if I should update CHANGELOG as there is nothing in it right now

**Comment by justin808** [comment]
@rtivital Please see how we do this:

https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md

and 

https://github.com/shakacode/bootstrap-loader

**Comment by rtivital** [comment]
@justin808 Changelog is done

**Comment by justin808** [comment]
Thanks @rtivital!

**Pull request merged**
