### PR TITLE
Fix pure sass export file

### PR DESCRIPTION
**Pull request by serheyShmyg**
This change is [Reviewable](https://reviewable.io/reviews/shakacode/sass-resources-loader/21)

### CODE REVIEW

**Comment by justin808** [comment]
@serheyShmyg can you please explain the issue that this change solves?

CC: @alexfedoseev

**Comment by serheyShmyg** [comment]
I can't build file with pure sass syntax (without curly brackets, semicolons ...). Loader concat this files without new line at the end of the file.

**Comment by justin808** [comment]
@alexfedoseev Please take a look at this one...

**Comment by justin808** [comment]
@alexfedoseev Maybe we'll put this one and #16 into the 1.2.0 release and that's the last one for webpack v1 support.

**Pull request merged**
